[package]
name = "shellij"
version = "0.0.1"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.98"
clap = { version = "4.5.36", features = ["derive"] }
crossterm = "0.29.0"
indoc = "2.0.6"
openssh = "0.11.5"
regex = "1.11.1"
tokio = { version = "1.44.2", features = ["full"] }
